name: Deploy to Base Mainnet
on:
  workflow_dispatch:
  push:
    branches: [ "main", "release" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (cached)
        if: ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Node (no cache)
        if: ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Node info
        run: |
          node -v
          npm -v

      - name: Install
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
            npm ci
          else
            npm install --no-fund --no-audit
          fi

      - name: Build
        run: npm run build

      - name: Deploy (Base Mainnet)
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          BASE_MAINNET_RPC_URL: ${{ secrets.BASE_MAINNET_RPC_URL }}
          BASE_SEPOLIA_RPC_URL: ""
          BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}
        run: |
          npx hardhat run scripts/deploy.ts --network base_mainnet | tee deploy.log
          echo '### Deploy Output' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat deploy.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
